insert into operace (operace_id, nazev, popis, filtr, kod) values (1,'Střihání základního materiálu','','J0;J.;O.;N.;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (2,'Fazetovat hrany pro zlacení','imersní zlacení,  ≤ 2,0 mm','J0;J.;O.;N.;;;;;;;;;;','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (3,'Děrování a paketování','',';J.;O.;N.;4A;;;;;;;;;','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (4,'Mikrozaleptání (MEB)   v.v.','',';;;;;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (5,'Navalení fotorezistu   v.v.','',';;;;;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (6,'Vytvoření motivu   v.v.','',';;;;;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (7,'Kontrola a retuš motivu   v.v.','',';;;;;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (8,'Leptání (kyselé) +stripování rezistu   v.v.','',';;;;;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (9,'Děrování sesazovacích otvorů   v.v.','',';;;;;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (10,'Kontrola (nebo optický test)   v.v.','',';;;;;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (11,'Černění   v.v.','',';;;;;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (12,'Svařování   v.v.','',';;;;;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (13,'Laminace','',';;;;;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (14,'Frézování reg.značek Inspecta','',';;;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (15,'Ostřih po laminaci','',';;;;4A;;;;;;;;;','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (16,'Vrtání','',';J.;O.;N.;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (17,'Vrtání s parametry Arlon','Arlon, Roger, Duroid, Diclad',';J.;O.;N.;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (18,'Vrtání drp. - zaplnované otvory','zaplnované otvory',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (19,'Vrtani se slepými otvory - strana A','slepé otvory ze str. A',';;;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (20,'Vrtani se slepými otvory - strana Z','slepé otvory ze str. Z',';;;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (21,'Vrtani se slepými otvory oboustranne','slepé otvory oboustranně',';;;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (22,'Profuk otvorů tlakovým vzduchem',' pro otvory ≤ 0,25 mm',';J.;O.;N.;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (23,'Ostřih dle vrtaných značek','',';;;;;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (24,'Fazetovat hrany pro zlacení','imersní zlacení, ≤ 2,0 mm',';;;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (25,'Kartacovani','',';;O.;N.;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (26,'Kartáčování jednostranné - jen strana Cu','','J0;J.;;;;;;;;;;;;','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (27,'Sušení 90 min při 110 oC','pro materál Diclad',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (28,'Sušení 2h při 150 oC','pro materiál is620',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (29,'Čištění v ultrazvukové myčce 10 min',' pro otvory ≤ 0,35 mm',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (30,'Čištění v ultrazvukové myčce 30 min',' pro otvory ≥ 0,40 mm',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (31,'NEOPACT-standardní','',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (32,'NEOPACT-2x = prg 1 + 7',' pro otvory ≤ 0,30 mm,Roger 4003 C, 3010, 3250B, zaplnované otvory',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (33,'NEOPACT-3x = prg 1+7+7','pro Arlony, Diclad',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (34,'NEOPACT-4x = prg 1+1+1+1','pro duroid 5880',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (35,'Kontrola pokovení otvorů technologem - nechat v regálu','Arlon, Diclad, Duroid,zaplnované otvory',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (36,'Cu-Sn- CELOPLOŠNÉ galvanické prokovení','zaplnované otvory',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (37,'Stripování Sn','zaplnované otvory',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (38,'Mikrozaleptání (MEB)','zaplnované otvory',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (39,'Zasuseni v peci 30 min. 150oC','zaplnované otvory',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (40,'Zaplneni otvoru','zaplnované otvory',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (41,'Vytvrzeni plugin pasty 1 hod.  150oC','zaplnované otvory',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (42,'Kartacovani do odstraneni zbytků zaplnovací pasty','zaplnované otvory',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (43,'kontrola zaplnenych otvoru','zaplnované otvory',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (44,'vrtani dr2.','zaplnované otvory',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (45,'Kartacovani','zaplnované otvory',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (46,'Mikrozaleptání (MEB)','',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (47,'Mikrozaleptání (MEB) 3,0 m/min','Duroid, Arlon, Diclad',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (48,'Kartacovani','Dps se slepými otvory',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (49,'Navalení fotorezistu','','J0;J.;O.;N.;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (50,'Navalení fotorezistu typu MM !!! celoplošné galv. zlacení','celoplošné galvanické zlacení','J0;J.;O.;N.;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (51,'Vytvoření motivu','','J0;J.;O.;N.;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (52,'Kontrola a retuš motivu','','J0;J.;O.;N.;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (53,'Leptání (kyselé) +stripování rezistu  ','','J0;J.;;N.;;;;;;;;;;','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (54,'Volat technologa - uprava plochy','první výroba, 6.,7.,8. k.t.',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (55,'Cu-Sn galvanické prokovení','',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (56,'Cu-Sn galvanické prokovení 2x!','požadavek zákazníka 2x pokovení',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (57,'Cu-Sn galv. pokov - nechat v regálu, celoplošné galv. Au','celoplošné galvanické zlacení',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (58,'Stripování fotorezistu','',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (59,'Navalení fotoresistu pro krytí sl.otv. oboustranné ','slepé otvory oboustranně, AR ˃ 0,8',';;;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (60,'Navalení fotoresistu pro krytí sl.otv. str. A','slepé otvory ze str. A, AR ˃ 0,8',';;;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (61,'Navalalení fotoresistu pro krytí sl.otv. str. Z','slepé otvory ze str. Z, AR ˃ 0,8',';;;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (62,'Vytvoření motivu na sl.otv. oboustranně','slepé otvory oboustranně, AR ˃ 0,8',';;;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (63,'Vytvoření motivu na sl.otvorech str. A','slepé otvory ze str. A, AR ˃ 0,8',';;;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (64,'Vytvoření motivu na sl.otvorech str. Z ','slepé otvory ze str. Z, AR ˃ 0,8',';;;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (65,'Kontrola a retuš motivu slepych otvorů','slepé otvory AR ˃ 0,8',';;;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (66,'Leptání alkalické ','',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (67,'Leptání alkalické za asistence technologa ','8. k.t.',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (68,'Stripování rezistu slepých otvorů','slepé otvory, AR ˃ 0,8',';;;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (69,'Stripování Sn','',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (70,'Mikrozaleptání (MEB)','8. k.t., ',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (71,'Mikrozaleptání (MEB) 3,0 m/min','Duroid, Arlon, Diclad, Roger','J0;J.;O.;N.;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (72,'Kartáčování po stripu Sn','',';;O.;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (73,'Kartacovani','','J0;J.;;N.;;;;;;;;;;','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (74,'Kontrola','','J0;J.;O.;N.;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (75,'Optický test po stripu','v případě galvanicky zlacených konektorů nebo pokud to zákazník vyžaduje','J0;J.;O.;N.;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, filtr, kod) values (76,'Elektricky test','v případě galvanicky zlacených konektorů NELZE',';;;;4A;6A;8A;10A;12A;4B;6B;8B;10B;12B','');
insert into operace (operace_id, nazev, popis, kod) values (77,'Kartacovani','','MA;MB;MX;PA;PB;PX');
insert into operace (operace_id, nazev, popis, kod) values (78,'Kartáčování jednostranné - jen strana Cu','','MA;MB;MX;PA;PB;PX');
insert into operace (operace_id, nazev, popis, kod) values (79,'Mikrozaleptání (MEB)','','MA;MB;MX;PA;PB;PX');
insert into operace (operace_id, nazev, popis, kod) values (80,'Nanášení nepájivé masky A - MASS ','','MA;');
insert into operace (operace_id, nazev, popis, kod) values (81,'Nanášení nepájivé masky B - MASS','','MB;');
insert into operace (operace_id, nazev, popis, kod) values (82,'Nanášení nepájivé masky AB - MASS','','MX;');
insert into operace (operace_id, nazev, popis, kod) values (83,'Nanášení nepájivé masky A - sítotisk bílá','bíla','MA;');
insert into operace (operace_id, nazev, popis, kod) values (84,'Nanášení nepájivé masky A - sítotisk černá','černá','MA;MB;MX;PA;PB;PX');
insert into operace (operace_id, nazev, popis, kod) values (85,'Nanášení nepájivé masky A - sítotisk červená','červena','MA;MB;MX;PA;PB;PX');
insert into operace (operace_id, nazev, popis, kod) values (86,'Nanášení nepájivé masky A - sítotisk modrá','modrá','MA;MB;MX;PA;PB;PX');
insert into operace (operace_id, nazev, popis, kod) values (87,'Nanášení nepájivé masky A - sítotisk zelená','zelená','MA;MB;MX;PA;PB;PX');
insert into operace (operace_id, nazev, popis, kod) values (88,'Nanášení nepájivé masky B - sítotisk bílá','bílá','MA;MB;MX;PA;PB;PX');
insert into operace (operace_id, nazev, popis, kod) values (89,'Nanášení nepájivé masky B - sítotisk černá','černá','MA;MB;MX;PA;PB;PX');
insert into operace (operace_id, nazev, popis, kod) values (90,'Nanášení nepájivé masky B - sítotisk červená','červená','MA;MB;MX;PA;PB;PX');
insert into operace (operace_id, nazev, popis, kod) values (91,'Nanášení nepájivé masky B - sítotisk modrá','modrá','MA;MB;MX;PA;PB;PX');
insert into operace (operace_id, nazev, popis, kod) values (92,'Nanášení nepájivé masky B - sítotisk zelená','zelená','MA;MB;MX;PA;PB;PX');
insert into operace (operace_id, nazev, popis, kod) values (93,'Nanášení nepájivé masky AB - sítotisk bílá','bílá','MX;PA;PB;PX');
insert into operace (operace_id, nazev, popis, kod) values (94,'Nanášení nepájivé masky AB - sítotisk černá','černá','MX;PA;PB;PX');
insert into operace (operace_id, nazev, popis, kod) values (95,'Nanášení nepájivé masky AB - sítotisk červená','červená','MX;PA;PB;PX');
insert into operace (operace_id, nazev, popis, kod) values (96,'Nanášení nepájivé masky AB - sítotisk modrá','modrá','MX;PA;PB;PX');
insert into operace (operace_id, nazev, popis, kod) values (97,'Nanášení nepájivé masky AB - sítotisk zelená','zelená','MX;PA;PB;PX');
insert into operace (operace_id, nazev, popis, kod) values (98,'Vytvoreni motivu masky A','','MA;');
insert into operace (operace_id, nazev, popis, kod) values (99,'Vytvoreni motivu masky B','','MB;');
insert into operace (operace_id, nazev, popis, kod) values (100,'Vytvoreni motivu masky AB','','MX;');
insert into operace (operace_id, nazev, popis, kod) values (101,'2.Nanášení nepájivé masky A - MASS ','','MA;');
insert into operace (operace_id, nazev, popis, kod) values (102,'2.Nanášení nepájivé masky B - MASS','','MB;');
insert into operace (operace_id, nazev, popis, kod) values (103,'2.Nanášení nepájivé masky AB - MASS','','MX;');
insert into operace (operace_id, nazev, popis, kod) values (104,'2.Nanášení nepájivé masky A - sítotisk','','MA;');
insert into operace (operace_id, nazev, popis, kod) values (105,'2.Nanášení nepájivé masky B - sítotisk','','MB;');
insert into operace (operace_id, nazev, popis, kod) values (106,'2.Nanášení nepájivé masky AB - sítotisk','','MX;');
insert into operace (operace_id, nazev, popis, kod) values (107,'2.Vytvoreni motivu masky A','','MA;');
insert into operace (operace_id, nazev, popis, kod) values (108,'2.Vytvoreni motivu masky B','','MB;');
insert into operace (operace_id, nazev, popis, kod) values (109,'2.Vytvoreni motivu masky AB','','MX;');
insert into operace (operace_id, nazev, popis, kod) values (110,'Potisk NEWPRINT A','','PA;');
insert into operace (operace_id, nazev, popis, kod) values (111,'Potisk NEWPRINT AB','','PX;');
insert into operace (operace_id, nazev, popis, kod) values (112,'Potisk NEWPRINT B','','PB;');
insert into operace (operace_id, nazev, popis, kod) values (113,'Kontrola před vytvrzením','','MA;MB;MX;');
insert into operace (operace_id, nazev, popis, kod) values (114,'Vytvrzení','','MA;MB;MX;');
insert into operace (operace_id, nazev, popis, kod) values (115,'Potisk A sitotiskem, vytvrzeni','','PA;');
insert into operace (operace_id, nazev, popis, kod) values (116,'Potisk AB sitotiskem, vytvrzeni','','PX;');
insert into operace (operace_id, nazev, popis, kod) values (117,'Potisk B sitotiskem, vytvrzeni','','PB;');
insert into operace (operace_id, nazev, popis, kod) values (118,'Aktivace Cu, HAL','','H');
insert into operace (operace_id, nazev, popis, kod) values (119,'Kontrola po HAL','','H');
insert into operace (operace_id, nazev, popis, kod) values (120,'Elektricky test','','H');
insert into operace (operace_id, nazev, popis, kod) values (121,'Kontrola pred imersnim zlacenim','','I');
insert into operace (operace_id, nazev, popis, kod) values (122,'Lepit hrany před zlacením',' ˃ 2,0 mm','I');
insert into operace (operace_id, nazev, popis, kod) values (123,'Imersni zlaceni','','I');
insert into operace (operace_id, nazev, popis, kod) values (124,'Kontrola po imersnim zlaceni','','I');
insert into operace (operace_id, nazev, popis, kod) values (125,'Elektricky test','','I');
insert into operace (operace_id, nazev, popis, kod) values (126,'Kontrola pred imersnim cinovanim','','C');
insert into operace (operace_id, nazev, popis, kod) values (127,'Stripování + imersni cinovani','','C');
insert into operace (operace_id, nazev, popis, kod) values (128,'Kontrola po imersnim cinovani','','C');
insert into operace (operace_id, nazev, popis, kod) values (129,'Elektricky test','','C');
insert into operace (operace_id, nazev, popis, kod) values (130,'Stripování cínu + celoplošné galvanické zlacení','','Q');
insert into operace (operace_id, nazev, popis, kod) values (131,'Stripování fotorezistu','','Q');
insert into operace (operace_id, nazev, popis, kod) values (132,'Leptání alkalické ','','Q');
insert into operace (operace_id, nazev, popis, kod) values (133,'Kontrola po celoplošném galvanickém zlacení','','Q');
insert into operace (operace_id, nazev, popis, kod) values (134,'Elektricky test','','Q');
insert into operace (operace_id, nazev, popis, kod) values (136,'Navalení fotoresistu před pokovením konektoru','','Z');
insert into operace (operace_id, nazev, popis, kod) values (137,'Vytvoření motivu pro pokovení konektoru','','Z');
insert into operace (operace_id, nazev, popis, kod) values (138,'Kontrola a retuš krycího fotoresistu pro konektory','','Z');
insert into operace (operace_id, nazev, popis, kod) values (139,'Galvanicke zlaceni primych konektoru','','Z');
insert into operace (operace_id, nazev, popis, kod) values (140,'Stripování fotorezistu','','Z');
insert into operace (operace_id, nazev, popis, kod) values (141,'Kontrola zlacení konektorů','','Z');
insert into operace (operace_id, nazev, popis, kod) values (143,'mytí saponátem','thermalclad','G');
insert into operace (operace_id, nazev, popis, kod) values (144,'mytí Thermalclad (linka po HAL)','thermalclad','G');
insert into operace (operace_id, nazev, popis, kod) values (145,'Stripování (striper cínu)','thermalclad','G');
insert into operace (operace_id, nazev, popis, kod) values (146,'Nanesení organického povlaku','','G');
insert into operace (operace_id, nazev, popis, kod) values (147,'Kontrola po organickém povlaku','','G');
insert into operace (operace_id, nazev, popis, kod) values (149,'tisk snímatelné masky A','','SA');
insert into operace (operace_id, nazev, popis, kod) values (150,'tisk snímatelné masky B','','SB');
insert into operace (operace_id, nazev, popis, kod) values (151,'aplikace kaptonové pásky','','SA;SB');
insert into operace (operace_id, nazev, popis, kod) values (153,'karbonová pasta na straně A','','V1A');
insert into operace (operace_id, nazev, popis, kod) values (154,'karbonová pasta na straně B','','V1B');
insert into operace (operace_id, nazev, popis, kod) values (155,'karbonová pasta na straně A i B','','V2X');
insert into operace (operace_id, nazev, popis, kod) values (156,'Drazkovani - bez úpravy panelu','','D1');
insert into operace (operace_id, nazev, popis, kod) values (157,'Drazkovani - s úpravou okolí ','','D1');
insert into operace (operace_id, nazev, popis, kod) values (158,'Drazkovani + rozlamani panelu','','D1');
insert into operace (operace_id, nazev, popis, kod) values (159,'Frézování výřezů','','F1');
insert into operace (operace_id, nazev, popis, kod) values (160,'Frézování tvaru','','F2');
insert into operace (operace_id, nazev, popis, kod) values (161,'Frézování tvaru + neprokovený program','','F2');
insert into operace (operace_id, nazev, popis, kod) values (162,'Rozstřih + dokončení tvaru','','R');
insert into operace (operace_id, nazev, popis, kod) values (163,'Vystupní kontrola','','');
insert into operace (operace_id, nazev, popis, kod) values (164,'Expedice','','');
